name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.9.0
      with:
        version: 'latest'
        project_id: your-gcp-project-id
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate to GCP
      run: gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}

    - name: Deploy to App Engine
      run: gcloud app deploy app.yaml --quiet
