name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/francesca-app:$GITHUB_SHA .

    - name: Push Docker image to Google Container Registry
      run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/francesca-app:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy francesca-app \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/francesca-app:$GITHUB_SHA \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
